services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     admin.refresh_apikeys:
        class: AdminBundle\Service\RefreshApiKeys
        arguments: ['@doctrine.orm.entity_manager']

     admin.change_user_status:
        class: AdminBundle\Service\ChangeUserStatus
        arguments: ['@doctrine.orm.entity_manager']