user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

user-api:
    type: rest
    resource: "@UserBundle/Resources/config/routing-api.yml"
    prefix:   /user-api

messenger:
    resource: "@MessengerBundle/Resources/config/routing.yml"
    prefix:   /

messenger-api:
    type: rest
    resource: "@MessengerBundle/Resources/config/routing-api.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

nelmio_doc_api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
