messages:
    type:     rest
    resource: '@MessengerBundle/Controller/MessagesController.php'
    prefix: /

conversations:
    type:     rest
    resource: '@MessengerBundle/Controller/ConversationsController.php'
    prefix: /
