messenger_home:
    path:   /
    defaults: { _controller: MessengerBundle:Default:index }

messenger_new_conversation:
    path:     /new/conversation/{user1id}/{user2id}
    defaults: { _controller: MessengerBundle:Default:newConversation }

messenger_new_message:
    path:   /new/message/{conversation}
    defaults: { _controller: MessengerBundle:Default:newMessage }
